<?php

/**
 * This is the model base class for the table "projects".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Projects".
 *
 * Columns in table "projects" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $short_name
 * @property string $image
 * @property string $logo
 * @property string $icon
 * @property integer $type
 * @property integer $billable_effort
 * @property integer $total_effort
 * @property integer $actual_effort
 * @property integer $discovery_phase_starts
 * @property integer $development_phase_starts
 * @property integer $end_development_phase_starts
 * @property integer $uat_phase_starts
 * @property string $resources
 * @property integer $ordering
 *
 */
abstract class BaseProjects extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'projects';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Projects|Projects', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('type, billable_effort, total_effort, actual_effort, discovery_phase_starts, development_phase_starts, end_development_phase_starts, uat_phase_starts, ordering', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>120),
			array('short_name', 'length', 'max'=>30),
			array('image, logo, icon', 'length', 'max'=>250),
			array('resources', 'safe'),
			array('name, short_name, image, logo, icon, type, billable_effort, total_effort, actual_effort, discovery_phase_starts, development_phase_starts, end_development_phase_starts, uat_phase_starts, resources, ordering', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, short_name, image, logo, icon, type, billable_effort, total_effort, actual_effort, discovery_phase_starts, development_phase_starts, end_development_phase_starts, uat_phase_starts, resources, ordering', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'short_name' => Yii::t('app', 'Short Name'),
			'image' => Yii::t('app', 'Image'),
			'logo' => Yii::t('app', 'Logo'),
			'icon' => Yii::t('app', 'Icon'),
			'type' => Yii::t('app', 'Type'),
			'billable_effort' => Yii::t('app', 'Billable Effort'),
			'total_effort' => Yii::t('app', 'Total Effort'),
			'actual_effort' => Yii::t('app', 'Actual Effort'),
			'discovery_phase_starts' => Yii::t('app', 'Discovery Phase Starts'),
			'development_phase_starts' => Yii::t('app', 'Development Phase Starts'),
			'end_development_phase_starts' => Yii::t('app', 'End Development Phase Starts'),
			'uat_phase_starts' => Yii::t('app', 'Uat Phase Starts'),
			'resources' => Yii::t('app', 'Resources'),
			'ordering' => Yii::t('app', 'Ordering'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('short_name', $this->short_name, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('logo', $this->logo, true);
		$criteria->compare('icon', $this->icon, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('billable_effort', $this->billable_effort);
		$criteria->compare('total_effort', $this->total_effort);
		$criteria->compare('actual_effort', $this->actual_effort);
		$criteria->compare('discovery_phase_starts', $this->discovery_phase_starts);
		$criteria->compare('development_phase_starts', $this->development_phase_starts);
		$criteria->compare('end_development_phase_starts', $this->end_development_phase_starts);
		$criteria->compare('uat_phase_starts', $this->uat_phase_starts);
		$criteria->compare('resources', $this->resources, true);
		$criteria->compare('ordering', $this->ordering);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}