<?php

/**
 * This is the model base class for the table "human_resources".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HumanResources".
 *
 * Columns in table "human_resources" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $user_id
 * @property string $division_id
 * @property string $avatar
 * @property string $email
 * @property string $skype
 * @property string $position
 *
 */
abstract class BaseHumanResources extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'human_resources';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'HumanResources|HumanResources', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, user_id, skype', 'length', 'max'=>60),
			array('division_id', 'length', 'max'=>10),
			array('avatar, email', 'length', 'max'=>250),
			array('position', 'safe'),
			array('name, user_id, division_id, avatar, email, skype, position', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, user_id, division_id, avatar, email, skype, position', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'user_id' => Yii::t('app', 'User'),
			'division_id' => Yii::t('app', 'Division'),
			'avatar' => Yii::t('app', 'Avatar'),
			'email' => Yii::t('app', 'Email'),
			'skype' => Yii::t('app', 'Skype'),
			'position' => Yii::t('app', 'Position'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('division_id', $this->division_id, true);
		$criteria->compare('avatar', $this->avatar, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('skype', $this->skype, true);
		$criteria->compare('position', $this->position, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}